name: Code quality checks

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  lint:
    runs-on: ubuntu-latest

    container:
      image: python:3.11-slim

    steps:
    - name: install deps
      run: |
        apt-get update
        apt-get install -y --no-install-recommends python3-pip git libatomic1
        python -m pip install --upgrade pip
        if [ -f requirements.txt ]
        then
            pip install -r requirements.txt
        fi
        pip install pylint ruff pyright

    - name: git clone
      uses: actions/checkout@v6
      with:
        fetch-depth: 0

    - name: pylint
      run: |
        git config --global --add safe.directory '*'
        pylint $(git ls-files '*.py' |grep -v contrib)

    - name: ruff check
      run: |
        ruff check .

    - name: pyright
      run: |
        git config --global --add safe.directory '*'
        pyright $(git ls-files '*.py' |grep -v contrib)

